# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'BookSelf' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'SDWebImage','~>5.0'
pod 'Firebase/Core'
pod 'MessageKit'
  # Pods for BookSelf

end
